version: '3'
services:

  mysql:
    image: "mysql:5.7.10"
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_USER=$MYSQL_USERNAME
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
    networks:
      - backend
    volumes:
      - ~/docker/mysql-data:/var/lib/mysql
  
  node:
    build: .
    image: nodejs-image
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    environment:
      - PORT=$PORT
      - NODE_ENV=$NODE_ENV
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_USER=$MYSQL_USERNAME
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
    ports:
      - 3000:3000
    depends_on:
      - mysql
    volumes:
      - ./:/node/app/
    networks:
      - backend


networks:
  backend:
    driver: 'bridge'
